import { JSDOM } from 'jsdom';
import fs from 'fs';
const html=fs.readFileSync('/home/claude/DwarfWiki/static/index.html','utf8');
const dom=new JSDOM(html,{runScripts:'outside-only',url:'http://127.0.0.1:5000/',pretendToBeVisual:true});
const {window}=dom;
window.HTMLCanvasElement.prototype.getContext=function(){const n=()=>{};return{canvas:this,fillRect:n,drawImage:n,beginPath:n,arc:n,fill:n,stroke:n,save:n,restore:n,measureText:()=>({width:10}),createImageData:()=>({data:new Uint8ClampedArray(4)}),getImageData:()=>({data:new Uint8ClampedArray(4)}),putImageData:n,clearRect:n,moveTo:n,lineTo:n,closePath:n,translate:n,fillText:n};};
window.fetch=(u,o)=>fetch(typeof u==='string'&&u.startsWith('/')?'http://127.0.0.1:5000'+u:u,o);
window.Image=class{constructor(){this.complete=true;this.naturalWidth=1;} set src(v){this.onload&&setTimeout(()=>this.onload(),1);} get src(){return '';}};
window.confirm=()=>true;
const errors=[]; window.onerror=m=>errors.push(m);
process.on('unhandledRejection',r=>errors.push('rejection: '+(r&&r.message||r)));
for(const f of ['vectorborders.js','map.js','wall.js','adv_data.js','adventurer.js'])
  window.eval(fs.readFileSync('/home/claude/DwarfWiki/static/'+f,'utf8'));
window.eval(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
await window.eval('boot()'); await new Promise(r=>setTimeout(r,1000));
const d=window.document;
console.log('=== image style page ===');
window.eval("location.hash='#/imagestyle'"); await new Promise(r=>setTimeout(r,150));
await window.eval('route()'); await new Promise(r=>setTimeout(r,1200));
console.log('  sections:', d.querySelectorAll('.pr-sec').length);
console.log('  variation seeds:', d.querySelectorAll('.pr-imgseeds .pr-item').length);
console.log('  status box shown:', !!d.querySelector('.upd-box'));
console.log('  quality inputs:', d.querySelectorAll('.pr-sec input[type=number]').length);
console.log('=== entity page buttons ===');
window.eval("location.hash='#/w/region1/hf/1'"); await new Promise(r=>setTimeout(r,150));
await window.eval('route()'); await new Promise(r=>setTimeout(r,2500));
console.log('  Draw portrait button:', /drawPortrait\(\)/.test(d.getElementById('view').innerHTML));
console.log('  Draw this scene in Tools:', /drawScene\(/.test(d.getElementById('view').innerHTML));
console.log('=== failure path explains itself ===');
window.eval('drawPortrait()'); await new Promise(r=>setTimeout(r,4000));
const modal=d.getElementById('modal').innerHTML;
console.log('  modal mentions image server:', /image server|Forge/i.test(modal));
console.log('  says nothing is uploaded:', /uploaded anywhere|own machine/i.test(modal));
console.log('\nERRORS:', errors.length?errors.join('\n  '):'none');
