import { JSDOM } from 'jsdom';
import fs from 'fs';
const html=fs.readFileSync('/home/claude/DwarfWiki/static/index.html','utf8');
const dom=new JSDOM(html,{runScripts:'outside-only',url:'http://127.0.0.1:5000/',pretendToBeVisual:true});
const {window}=dom;
window.HTMLCanvasElement.prototype.getContext=function(){const n=()=>{};return{canvas:this,fillRect:n,drawImage:n,beginPath:n,arc:n,fill:n,stroke:n,save:n,restore:n,measureText:()=>({width:10}),createImageData:()=>({data:new Uint8ClampedArray(4)}),getImageData:()=>({data:new Uint8ClampedArray(4)}),putImageData:n,clearRect:n,moveTo:n,lineTo:n,closePath:n,translate:n,fillText:n};};
window.fetch=(u,o)=>fetch(typeof u==='string'&&u.startsWith('/')?'http://127.0.0.1:5000'+u:u,o);
window.Image=class{constructor(){this.complete=true;this.naturalWidth=1;} set src(v){this.onload&&setTimeout(()=>this.onload(),1);} get src(){return '';}};
window.confirm=()=>true;
const errors=[]; window.onerror=m=>errors.push(m);
process.on('unhandledRejection',r=>errors.push('rejection: '+(r&&r.message||r)));
for(const f of ['vectorborders.js','map.js','wall.js','adv_data.js','adventurer.js'])
  window.eval(fs.readFileSync('/home/claude/DwarfWiki/static/'+f,'utf8'));
window.eval(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
await window.eval('boot()'); await new Promise(r=>setTimeout(r,1000));
const d=window.document;
console.log('logo in header:', !!d.querySelector('.brand-logo'));
window.eval("location.hash='#/w/region1/hf/1'"); await new Promise(r=>setTimeout(r,150));
await window.eval('route()'); await new Promise(r=>setTimeout(r,2500));
console.log('article grid:', !!d.querySelector('.article'));
console.log('contents rail:', !!d.querySelector('.rail .toc'), '| entries:', d.querySelectorAll('.rail .toc-list li').length);
console.log('rail toggle button:', !!d.querySelector('.rail-toggle'));
console.log('body data-etype:', d.body.getAttribute('data-etype'));
console.log('body has-rail:', d.body.classList.contains('has-rail'));
console.log('factbox present:', !!d.querySelector('.factbox'));
console.log('portrait in vital record:', !!d.querySelector('.fb-portrait'), '(none expected — no images on this figure)');
window.eval('toggleRail()'); await new Promise(r=>setTimeout(r,100));
console.log('after toggle, rail hidden:', d.body.classList.contains('rail-hidden'));
window.eval('toggleRail()');
console.log('\nERRORS:', errors.length?errors.join('\n  '):'none');
